Total Steps = SUM ( gold_daily_health[steps] )
Sleep Hours = DIVIDE ( SUM ( gold_daily_health[sleep_minutes] ), 60.0 )
Average Heart Rate = AVERAGE ( gold_daily_health[avg_heart_rate] )
Average Blood Oxygen = AVERAGE ( gold_daily_health[avg_blood_oxygen] )
Average Skin Temperature = AVERAGE ( gold_daily_health[avg_skin_temperature] )
Average Energy Score = AVERAGE ( gold_daily_health[energy_score] )
Latest Metric Time = MAX ( gold_daily_health[last_metric_event_utc] )
Data Freshness Minutes = DATEDIFF ( [Latest Metric Time], UTCNOW(), MINUTE )
Steps 7D Average = AVERAGEX ( DATESINPERIOD ( gold_daily_health[health_date], MAX(gold_daily_health[health_date]), -7, DAY ), [Total Steps] )
Sleep 7D Average = AVERAGEX ( DATESINPERIOD ( gold_daily_health[health_date], MAX(gold_daily_health[health_date]), -7, DAY ), [Sleep Hours] )
Successful Runs = CALCULATE ( COUNTROWS(pipeline_runs), pipeline_runs[status] = "SUCCEEDED" )
Failed Quality Checks = CALCULATE ( COUNTROWS(data_quality), data_quality[status] = "FAIL" )
